name: Check code with Pylint

on:
  push:
    # branches: [ master ]
    paths:
      - '**.py'
  pull_request:
    branches: [ master ]
    paths:
      - '**.py'
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          echo "Installed dependencies"

      - name: Lint with pylint
        run: |
          echo "Linting monitoring directory..."
          pylint --disable=C0111,C0103,C0301 --fail-under=7 monitoring/