name: Starts a stopped Minecraft Server!

on:
  push:
    branches:
      - master        
  workflow_dispatch:
    inputs:
      restart:
        description: 'Type "yes" to confirm restarting the server'
        required: true
        default: 'no'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace

      - name: Echo Echo
        run: echo "Echo Echo"

      - name: Restart Minecraft Server
        if: ${{ github.event.inputs.restart == 'yes' && github.event_name == 'workflow_dispatch' }}
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_HOST_IP }} "sudo systemctl restart minecraft.service"
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.SERVER_HOST_IP }} "sudo systemctl status minecraft.service"